NoSelection:
Linear:
  threshold: 
    - 0.5
    - 0.95
    - step: 0.05
Correlation:
  threshold: 
    - 0.5
    - 0.95
    - step: 0.05
MutualInformation:
  threshold: 
    - 0.5
    - 0.95
    - step: 0.05
TimeSelectionLayer:
  regularization: 
    - 0.00001
    - 0.00005
    - 0.0001
    - 0.0005
    - 0.001
    - 0.005
    - 0.01