lstm:
  keep_dims: False
  layers:
    - 1
    - 3
  units:
    - 4
    - 64
  dropout:
    - 0.0
    - 0.5
  batch_size:
    - 16
    - 128
  lr:
    - 0.0001
    - 0.01
  type: tensorflow

dense:
  keep_dims: False
  layers:
    - 1
    - 3
  units:
    - 4
    - 64
  dropout:
    - 0.0
    - 0.5
  batch_size:
    - 16
    - 128
  lr:
    - 0.0001
    - 0.01
  type: tensorflow
