TimeSelectionLayer:
  regularization: 
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
    - 0.01
    
TimeSelectionLayerConstant:
  regularization: 
    - 0.000001
    - 0.00001
    - 0.0001
    - 0.001
    - 0.01